% This function visualizes the analytics of portfolio and save the plots as a pdf 

function PFReport(analytics, parameter, reportfile)
fts1 = [analytics.cumret, analytics.TO, analytics.TC, analytics.IC...
    , analytics.signalexp, analytics.nlong, analytics.activeness...
    , analytics.autocorr];
fts2 = analytics.yearlyreturn;

title = {'Cumulative Active Return (After Cost)'...
    ,'Turnover Per Rebalance'...
    ,'Tranfer Coefficient'...
    ,'IC'...
    ,'Alpha Exposure'...
    ,'NO. of long names'...
    ,'Activeness'...
    ,'Alpha Auto Correlation'...
    };
notes = {['Ann. Return = ',num2str(analytics.annual_ret*100,3),'%, Ann. Vol = ',num2str(analytics.annual_vol*100,3),'%, IR = ', num2str(analytics.IR,3), ', Max. DD = ', num2str(analytics.max_DD*100,3), '%']...
    ,['Avg Turnover Per Rebalance= ',num2str(analytics.avg_TO*100,3),'%']...
    ,['Avg TC = ',num2str(analytics.avg_TC,3)]...
    ,['Avg IC = ',num2str(analytics.avg_IC*100,3),'%, IC Vol = ',num2str(analytics.std_IC*100,3),'%, IC mean/stdev= ', num2str(analytics.IR_IC,3)]...
    ,['Avg Alpha Exposure = ',num2str(analytics.avg_exp,3)]...
    ,['Avg NO. of long names = ',num2str(analytics.avg_n,3)]...
    ,['Avg Activeness = ',num2str(analytics.avg_active*100,3),'%']...
    ,['Avg Auto Corr = ',num2str(analytics.avg_acorr*100,3),'%']...
    };

style = {'b'};  
range = {1,2,3,4,5,6,7,8};

tsplot(fts1, 'group', eye(8), 'title', title...
    , 'notes', notes...
    , 'drawfun', {@plot, @bar, @plot, @bar, @bar, @plot, @bar, @bar}...
    , 'ymin', [NaN, 0, 0, NaN, 0, 0, 0, 0]...
    , 'ymax', [NaN, 1, 1, NaN, NaN, NaN, 1, 1]...
    , 'layout', [4,2]...
    , 'style', style...
    , 'range', range...
    );

if nargin > 2
    % add title to the report
    hold on
    axes('Position', [0, 0.98, 1, 0.06], 'visible', 'off');
    
    gicsname = {'sector','industry grp','industry','sub-industry'};
    
    reportdesc1 = ['\fontsize{8}\bf ',reportfile,' - pickup = ',num2str(parameter.pickup,4),', actbet = ', num2str(parameter.actbet,4)...
    ,', tradetoadv = ',num2str(parameter.tradetoadv,4),', holdtoadv = ',num2str(parameter.holdtoadv,4),', capital = ',num2str(parameter.capital)];
    reportdesc2 = ['\fontsize{8}\bf maxto = ',num2str(parameter.maxto),', tcost = ',num2str(parameter.tcost,3)...
    ,', sectorbet = ',num2str(parameter.sectorbet,4),'(on ',gicsname{parameter.sectorlevel},' level), ctrybet = ',num2str(parameter.ctrybet,4), ', tailactbet = ',num2str(parameter.tailactbet,4),', propactbet = ',parameter.propactbet];
    reportdesc1 = strrep(reportdesc1,'_','\_');
    reportdesc2 = strrep(reportdesc2,'_','\_');
    text(0.5,0,reportdesc1, 'HorizontalAlignment', 'center');
    text(0.5,-0.3,reportdesc2, 'HorizontalAlignment', 'center');
    
    saveas(gcf, [reportfile, '.pdf'], 'pdf');
%     saveas(gcf, [reportfile, '.eps'], 'psc2');
%     system(['y:\louis.luo\TeX\miktex\bin\epstopdf ' reportfile, '.eps']);
    close;
end 

return